
export const GET_DOGS_REQUEST = 'GET_DOG_REQUEST';
export const GET_RANDOM_DOGS_SUCCESS = 'GET_RANDOM_DOGS_SUCCESS';
export const GET_DOGS_BY_BREED_SUCCESS = 'GET_DOGS_BY_BREED_SUCCESS';
export const GET_DOGS_FAILURE = 'GET_DOG_FAILURE';
export const SET_FILTERS = 'SET_FILTERS';

export const START_GAME = 'START_GAME';
export const END_GAME = 'END_GAME';

export const GET_BREEDS_REQUEST = 'GET_BREEDS_REQUEST';
export const GET_BREEDS_SUCCESS = 'GET_BREEDS_SUCCESS';
export const GET_BREEDS_FAILURE = 'GET_BREEDS_FAILURE';

export const REMOVE_DOG_PAIR = 'REMOVE_DOG_PAIR';
