
export const GET_DOG_REQUEST = 'GET_DOG_REQUEST';
export const GET_DOG_SUCCESS = 'GET_DOG_SUCCESS';
export const GET_DOG_FAILURE = 'GET_DOG_FAILURE';

export const GET_BREEDS_REQUEST = 'GET_BREEDS_REQUEST';
export const GET_BREEDS_SUCCESS = 'GET_BREEDS_SUCCESS';
export const GET_BREEDS_FAILURE = 'GET_BREEDS_FAILURE';

export const REMOVE_DOG_PAIR = 'REMOVE_DOG_PAIR';
